name: bond_form_riverpod
description: Form is a Bond package provides a convenient way to handle Form using riverpod.
version: 0.0.3+1
repository: https://github.com/onestudio-co/bond-core/tree/main/packages/form/packages/bond_form_riverpod
homepage: https://github.com/onestudio-co/flutter-bond

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  riverpod: ^2.6.1

  bond_form: ^0.0.5