name: bond_app_analytics
description: Bond package provides a convenient way to log analytics events
version: 0.0.1+3
homepage: https://github.com/onestudio-co/flutter-bond

environment:
  sdk: ">=2.16.0 <3.0.0"
