name: bond_form
description: Form is a Bond package provides a convenient way to handle Form.
version: 0.0.22+19
homepage: https://github.com/onestudio-co/flutter-bond
repository: https://github.com/onestudio-co/bond-core/tree/main/packages/form

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.8.0
  mime: ^1.0.5
  intl: ^0.20.2
  collection: ^1.18.0
  bond_core: ^0.0.3

dev_dependencies:
  intl_translation: ^0.20.0
