name: bond_form
description: Form is a Bond package provides a convenient way to handle Form.
version: 0.0.1+3
homepage: https://github.com/onestudio-co/flutter-bond

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.8.0
  intl: ^0.18.0

  bond_core: ^0.0.1+2


dev_dependencies:
  intl_translation: ^0.18.2