name: bond_notifications
description: Bond package provides a convenient way to handle notifications.
version: 0.0.1+1
homepage: https://github.com/onestudio-co/flutter-bond

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.7.0
  json_serializable: ^6.5.4
  bond_core: ^0.0.1+1
  bond_network: ^0.0.1

